#!/bin/sh /etc/rc.common
# SPDX-FileCopyrightText: 2026 Andrey Tokarev
# SPDX-License-Identifier: LicenseRef-Flint-VPN-Noncommercial-1.0
# Web panel on :81 (:80 belongs to the GL.iNet admin UI).
START=99
USE_PROCD=1
start_service() {
  procd_open_instance
  procd_set_param command /usr/sbin/uhttpd -f -p 81 -h /www/flint -x /cgi-bin -I index.html
  procd_set_param respawn
  procd_close_instance
}
