#!/bin/sh /etc/rc.common
# DoH resolver for dnsmasq on 127.0.0.1:5053.
# Separate from GL's dnscrypt-proxy service, which only runs in GL "secure DNS" mode.
START=18
STOP=89
USE_PROCD=1
start_service() {
  procd_open_instance
  procd_set_param command /usr/sbin/dnscrypt-proxy -config /etc/dnscrypt-proxy2/gru-doh.toml
  procd_set_param file /etc/dnscrypt-proxy2/gru-doh.toml
  procd_set_param respawn
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}
