#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1
start_service() {
  # No config while there are no servers (see flint-node).
  [ -s /etc/xray/config.json ] || return 0
  procd_open_instance
  procd_set_param command /usr/bin/xray run -c /etc/xray/config.json
  procd_set_param env XRAY_LOCATION_ASSET=/usr/share/xray
  procd_set_param file /etc/xray/config.json
  procd_set_param respawn
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}
