#!/usr/bin/env python3
"""Rebuild config/nodes.conf from the provider subscription.

Usage: python tools/sub2nodes.py [--no-ip] [--grpc] [subscription_url]
The URL defaults to SUB_URL from config/gru.env. Only REALITY links over TCP
(+ xtls-rprx-vision) or gRPC are kept: that is what kit/files/etc/xray/template.json supports.
--no-ip skips servers given by a bare IP (GruVPN "white list" nodes).
--grpc also keeps gRPC nodes (or SUB_GRPC=1 in gru.env); off by default because the
provider's gRPC REALITY servers fail the handshake with the router's Xray 1.8.7.
Provider notices disguised as nodes (names starting with ❗) are always skipped.
"""
import base64
import ipaddress
import pathlib
import sys
import urllib.parse
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
ENV = ROOT / "config" / "gru.env"
OUT = ROOT / "config" / "nodes.conf"
USER_AGENT = "Happ/1.0"


def read_env():
    env = {}
    if ENV.exists():
        for line in ENV.read_text(encoding="utf-8").splitlines():
            if "=" in line and not line.lstrip().startswith("#"):
                key, value = line.split("=", 1)
                env[key.strip()] = value.strip().strip('"')
    return env


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    text = urllib.request.urlopen(req, timeout=30).read().decode("utf-8", "ignore")
    if "vless://" not in text:
        raw = text.strip()
        text = base64.b64decode(raw + "=" * (-len(raw) % 4)).decode("utf-8", "ignore")
    return [line.strip() for line in text.splitlines() if line.startswith("vless://")]


def flag_code(name):
    letters = [chr(ord(ch) - 0x1F1E6 + ord("a")) for ch in name[:2] if 0x1F1E6 <= ord(ch) <= 0x1F1FF]
    return "".join(letters) if len(letters) == 2 else ""


def is_ip(host):
    try:
        ipaddress.ip_address(host)
        return True
    except ValueError:
        return False


def main():
    args = sys.argv[1:]
    include_ip = "--no-ip" not in args
    env = read_env()
    include_grpc = "--grpc" in args or env.get("SUB_GRPC") == "1"
    args = [a for a in args if a not in ("--no-ip", "--include-ip", "--grpc")]
    url = args[0] if args else env.get("SUB_URL", "")
    if not url:
        sys.exit("No subscription URL: pass it as an argument or set SUB_URL in config/gru.env")

    nodes, used = [], set()
    for link in fetch(url):
        parts = urllib.parse.urlsplit(link)
        query = dict(urllib.parse.parse_qsl(parts.query))
        net = query.get("type", "tcp")
        if net not in ("tcp", "grpc") or query.get("security") != "reality":
            continue
        if net == "grpc" and not include_grpc:
            continue
        if net == "tcp" and query.get("flow") not in (None, "", "xtls-rprx-vision"):
            continue
        if net == "grpc" and (query.get("flow") or query.get("mode", "gun") != "gun"):
            continue
        if not all(query.get(k) for k in ("sni", "pbk")):
            continue
        name = urllib.parse.unquote(parts.fragment).strip()
        if name.startswith("\u2757"):
            continue
        host = parts.hostname
        if is_ip(host) and not include_ip:
            continue
        base = flag_code(name) or host.split(".")[0].split("-")[0]
        code, n = base, 2
        while code in used:
            code, n = f"{base}{n}", n + 1
        used.add(code)
        nodes.append((name, code, host, query["sni"], query["pbk"], query.get("sid") or "-", parts.username,
                      parts.port or 443, net, query.get("serviceName") or "-"))

    if not nodes:
        sys.exit("No supported REALITY nodes in the subscription")

    lines = ["# Generated by tools/sub2nodes.py. Columns: code address sni pbk sid uuid port net service"]
    for name, code, host, sni, pbk, sid, uuid, port, net, svc in nodes:
        lines.append(f"# {name}")
        lines.append(f"{code}  {host}  {sni}  {pbk}  {sid}  {uuid}  {port}  {net}  {svc}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"Wrote {OUT.relative_to(ROOT)}: {len(nodes)} nodes")
    for name, code, host, *_ in nodes:
        print(f"  {code:6} {host}")


if __name__ == "__main__":
    main()
